export const gadgets = [
  {
    id: 1,
    name: "Apple Watch",
    price: 150000,
    image: "/images/applewatch.jpg",
    description:
      "Stay connected and track your health with the Apple Watch. Features heart rate monitoring, fitness tracking, notifications, GPS, and water resistance in a sleek design.",
    category: "Smart Watch",
    brand: "Apple",
    stock: 25,
    rating: 4.9,
  },
  {
    id: 2,
    name: "Samsung Galaxy Tab",
    price: 500000,
    image: "/images/galaxytab.jpg",
    description:
      "A premium Android tablet with a stunning display, powerful processor, long-lasting battery, and S Pen support for work and entertainment.",
    category: "Tablet",
    brand: "Samsung",
    stock: 18,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Apple Ipad",
    price: 1000000,
    image: "/images/ipad.jpg",
    description:
      "Experience unmatched performance with the Apple iPad. Perfect for studying, business, gaming, and creative work with its Retina display and powerful chip.",
    category: "Tablet",
    brand: "Apple",
    stock: 15,
    rating: 5.0,
  },
  {
    id: 4,
    name: "Samsung Television",
    price: 800000,
    image: "/images/television.jpg",
    description:
      "A 4K Ultra HD Smart TV with vibrant colors, crystal-clear picture quality, built-in streaming apps, and immersive sound.",
    category: "Television",
    brand: "Samsung",
    stock: 10,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Sony Power Bank Set",
    price: 150000,
    image: "/images/powerbank.jpg",
    description:
      "A reliable high-capacity power bank set with fast charging technology to keep your devices powered all day.",
    category: "Power Bank",
    brand: "Sony",
    stock: 40,
    rating: 4.6,
  },
  {
    id: 6,
    name: "Airpods Pro",
    price: 180000,
    image: "/images/airpods.jpg",
    description:
      "Enjoy premium sound quality, Active Noise Cancellation, Transparency Mode, and all-day comfort with AirPods Pro.",
    category: "Wireless Earbuds",
    brand: "Apple",
    stock: 30,
    rating: 4.9,
  },
  {
    id: 7,
    name: "Canon Drone",
    price: 700000,
    image: "/images/drone.jpg",
    description:
      "Capture breathtaking aerial photos and videos with this high-performance Canon drone featuring 4K recording and GPS stabilization.",
    category: "Drone",
    brand: "Canon",
    stock: 8,
    rating: 4.8,
  },
  {
    id: 8,
    name: "iPhone 11 Pro Max",
    price: 420000,
    image: "/images/iphone11.jpg",
    description:
      "A premium smartphone with a Super Retina display, triple-camera system, Face ID security, and exceptional performance.",
    category: "Smartphone",
    brand: "Apple",
    stock: 20,
    rating: 4.9,
  },
  {
    id: 9,
    name: "JBL Headphone",
    price: 80000,
    image: "/images/headphone.jpg",
    description:
      "Enjoy deep bass, crystal-clear audio, and maximum comfort with JBL over-ear headphones featuring long battery life.",
    category: "Headphones",
    brand: "JBL",
    stock: 35,
    rating: 4.7,
  },
  {
    id: 10,
    name: "Mini Camera",
    price: 100000,
    image: "/images/minicamera.jpg",
    description:
      "A compact HD mini camera suitable for home security, travel, and outdoor adventures with excellent image quality.",
    category: "Camera",
    brand: "Sony",
    stock: 22,
    rating: 4.5,
  },
  {
    id: 11,
    name: "Sony Laptop",
    price: 600000,
    image: "/images/laptop.jpg",
    description:
      "A powerful laptop designed for professionals and students, featuring a fast processor, SSD storage, and long battery life.",
    category: "Laptop",
    brand: "Sony",
    stock: 12,
    rating: 4.8,
  },
  {
    id: 12,
    name: "Portable Speaker",
    price: 40000,
    image: "/images/speaker.jpg",
    description:
      "A compact Bluetooth speaker delivering rich sound, deep bass, and hours of uninterrupted music playback.",
    category: "Bluetooth Speaker",
    brand: "JBL",
    stock: 50,
    rating: 4.6,
  },
];